POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "zukaa",
    "password": "zu123"
}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "zukaaa",
    "password": "zu123",
    "email": "zu@gmail.com"
}
###

GET  http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}


