POST http://127.0.0.1:8000/myuserauth/login
Content-Type: application/json

{
    "username": "zuka",
    "password": "zu123"
}

###

POST http://127.0.0.1:8000/myuserauth/signup
Content-Type: application/json

{
    "username": "zukaaa1",
    "password": "zu123",
    "email": "zu@gmail.com"
}
###

GET  http://127.0.0.1:8000/myuserauth/test_token
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}

###

GET  http://127.0.0.1:8000/workouts/default-exercises
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}

###

GET  http://127.0.0.1:8000/workouts/get-default-exercises-with-ids
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{
    "exercises": [1, 4, 6]
}



###

POST  http://127.0.0.1:8000/workouts/create-workout-plan
Content-Type: application/json
Authorization: Token 27877389ab9a18086cfbd07f3749bfd4beac8df2

{
    "name": "Sung-jing-woo",
    "frequency": 3,
    "goal": "Increase Every Stat",
    "duration": 60
}

###

GET  http://127.0.0.1:8000/workouts/get-all-workout-plans
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}

###

POST  http://127.0.0.1:8000/workouts/create-workout-plan-exercise
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{
    "workout_plan": 2,
    "exercise": 1,
    "repetitions": 5,
    "sets": 2,
    "duration": 20,
    "distance": 0
}

###

GET  http://127.0.0.1:8000/workouts/get-workout-plan-exercises
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{
    "workout_plan": 2
}

###

GET  http://127.0.0.1:8000/workouts/get-frequency-choices
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}
###

GET  http://127.0.0.1:8000/workouts/get-goal-type-choices
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}

###

POST  http://127.0.0.1:8000/workouts/create-goal
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{
    "type": "weight",
    "weight_target": 70.0,
    "exercise": 9,
    "target_value": 90
}

###

PUT  http://127.0.0.1:8000/workouts/update-goal
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{
    "id": 1,
    "type": "exercise",
    "weight_target": 75.0,
    "exercise": 2,
    "target_value": 150
}

###

GET  http://127.0.0.1:8000/workouts/get-goal
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{
    "id": 1
}

###

GET  http://127.0.0.1:8000/workouts/get-all-goals
Content-Type: application/json
Authorization: Token 3f9718daa1bac31e9a8fa9289101c81d50a1019b

{}